import type { Metadata } from "next";
import { Geist, Geist_Mono, Spline_Sans, Oxanium } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import FooterCounter from "@/components/FooterCounter";
import AOSProvider from "@/components/aos-interactions/AOSProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const splineSans = Spline_Sans({
  variable: "--font-spline",
  subsets: ["latin"],
});

const oxanium = Oxanium({
  variable: "--font-oxanium",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${splineSans.variable} ${oxanium.variable} antialiased`}
      >
        <AOSProvider />
        <Navbar />
        {children}
        <FooterCounter />
        <Footer />
      </body>
    </html>
  );
}
